# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8080
    connection-timeout: 5000ms
    servlet:
      context-path: /sdb

# /info 端点的显示
info:
  name: @project.artifactId@
  version: @project.version@
  date: @maven.build.timestamp@
  description: @project.description@

spring:
    # 环境 dev|test|prod
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
          servlet:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host:
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
          pool:
              max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
              max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
              max-idle: 10      # 连接池中的最大空闲连接
              min-idle: 5       # 连接池中的最小空闲连接
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    mail:
        host: smtp.163.com
        username:
        password:
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                required: true
                enable: true

sdb:
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: www.senduobang.com
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

schedule:
    open: false

wechat:
  ma:
    msgDataFormat: JSON
    appid:
    secret:
    mchId:
    mchKey:
    keyPath:
    notifyUrl:
  mp:
    openAppId:
    openAppSecret:
    configs:
      - appid:
        secret:
        token:
        aesKey:

order:
  refund: false

kuaidi100:
  notifyUrl:
  kuaidi100Key:
  kuaidi100PollUrl:


